apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: iv6syglsa-python
  janus-idp.io/tekton: iv6syglsa-python
  backstage.io/kubernetes-id: iv6syglsa-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: iv6syglsa-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
